include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve

analyzer:
  errors:
    invalid_annotation_target: ignore
    implementation_imports: ignore

linter:
  rules:
    prefer_single_quotes: true
