include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve

analyzer:
  errors:
    invalid_annotation_target: ignore
    implementation_imports: ignore
    constant_identifier_names: ignore
    must_be_immutable: ignore

linter:
  rules:
    prefer_single_quotes: true
